version: '3.8'

services:
  postgres_db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telecom_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  sms_securing_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
